# Generated by Django 2.2.3 on 2019-08-09 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='类名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='公司名')),
                ('introduce', models.TextField(verbose_name='组的介绍')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='建组时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建组人')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_name', models.CharField(max_length=255, verbose_name='员工姓名')),
                ('em_company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_employees', to='daily.Company', verbose_name='所属公司')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='em_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='标签名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.Employees', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='日报创建时间')),
                ('content', models.TextField(default='没有日报', help_text='正文必须为MD格式', verbose_name='正文')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.Category', verbose_name='分类')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.Employees', verbose_name='汇报人')),
                ('tag', models.ManyToManyField(to='daily.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '日报',
                'verbose_name_plural': '日报',
                'ordering': ['created_time'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.Employees', verbose_name='创建人'),
        ),
    ]
