# Generated by Django 2.2.3 on 2019-08-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='em_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='em_name',
            new_name='name',
        ),
    ]
