# Generated by Django 2.2.3 on 2019-08-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20190809_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_employees', to='daily.Company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='员工姓名'),
        ),
    ]
