# Generated by Django 2.2.3 on 2019-08-11 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0006_auto_20190810_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'ordering': ['-created_time'], 'verbose_name': '日报', 'verbose_name_plural': '日报'},
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_founder', to='daily.Employees', verbose_name='建组人'),
        ),
    ]
