# Generated by Django 2.2.3 on 2019-08-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0007_auto_20190811_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='introduce',
            field=models.TextField(verbose_name='公司的介绍'),
        ),
    ]
